title: "ML & AI in Action"
author: "Jing Lu"
description: "Explore the Practical Side of ML & AI: Real-World Applications and Impact." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "ajingnk@mail.com"
twitter_username: "ajingnk"
github_username: "ajing"
linkedin_username: "jing-lu-a0b07123"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

comments_repo: ajing/ajing.github.io

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
future: true

rss: rss

kramdown:
  syntax_highlighter: rouge
highlighter: rouge
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
